version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: claims_test
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://test:test@db:5432/claims_test
      NODE_ENV: test
    volumes:
      - ./:/home/testuser/app
    command: npm run test:e2e

volumes:
  pgdata:
