version: '3.8'

services:
  test-runner:
    build: .
    environment:
      - NODE_ENV=test
      - BASE_URL=http://web:3000
      - API_BASE_URL=http://api:3001
    volumes:
      - ./reports:/app/reports
      - ./screenshots:/app/screenshots
    networks:
      - test-network

  web:
    image: nginx:alpine
    ports:
      - "3000:80"
    networks:
      - test-network

networks:
  test-network: {}