export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  CLAIMS_ADJUSTER = 'CLAIMS_ADJUSTER',
  WORKSHOP_MANAGER = 'WORKSHOP_MANAGER',
  WORKSHOP_TECHNICIAN = 'WORKSHOP_TECHNICIAN',
  INSURANCE_AGENT = 'INSURANCE_AGENT',
  ADMIN = 'ADMIN'
}
